project:
  type: website
  output-dir: "./_site"
  title: "Junto Technologies"

execute:
  enabled: true
  python: "./renv/python/virtualenvs/renv-python-3.11/bin/python"

website:
  favicon: "./assets/media/favicon.png"
  navbar:
    right:
      - text: "About Us"
        href: index.qmd
      - text: "Team"
        href: pages/team.qmd
      - text: "Services"
        href: pages/services.qmd
      - text: "Contact Us"
        href: pages/contact.qmd

format:
  html:
    theme: lumen
    css: assets/styles.css

editor: visual
