project:
  type: website
  output-dir: "."
  title: "Junto Technologies"

execute:
  enabled: true
  python: "./renv/python/virtualenvs/renv-python-3.11/bin/python"

website:
  favicon: "./media/favicon.png"
  navbar:
    right:
      - text: "About Us"
        href: index.qmd
      - text: "Team"
        href: team.qmd
      - text: "Team2"
        href: team_2.qmd
      - text: "Services"
        href: services.qmd
      - text: "Contact Us"
        href: contact.qmd

format:
  html:
    theme: lumen
    css: styles.css

editor: visual
